CREATE TABLE [dbo].[tblComments]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [RecipeId] UNIQUEIDENTIFIER NOT NULL, 
    [UserId] UNIQUEIDENTIFIER NOT NULL, 
    [Review] VARCHAR(500) NOT NULL, 
    [Rating] INT NOT NULL
)
