CREATE TABLE [dbo].[tblUser]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Email] VARCHAR(50) NOT NULL, 
    [Password] VARCHAR(50) NOT NULL, 
    [Picture] VARCHAR(250) NOT NULL, 
    [Description] VARCHAR(400) NOT NULL, 
    [AccessLevelId] UNIQUEIDENTIFIER NOT NULL
)
