BEGIN
	INSERT INTO tblRecipeInstruction VALUES
		(NEWID(), dbo.fnRecipeID('Blackened Shrimp Tacos'), 1, 'Preheat the oven to 300 degrees F - Wrap the tortillas in foil and place them on a baking sheet or pan', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Blackened Shrimp Tacos'), 2, 'Season the Shrimp - In a large bowl, combine the shrimp, blackening seasoning, and salt', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Blackened Shrimp Tacos'), 3, 'Warm the tortillas - Bake the foil-wrapped tortillas until they’re warmed through, about 10 minutes (if your tortillas are done before you finish the slaw and shrimp, turn off the oven, and leave the tortillas inside to stay warm until you are ready to assemble', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Blackened Shrimp Tacos'), 4, 'Make the cabbage slaw - In a large bowl, combine the cabbage, mayo, sugar, black pepper, and white vinegar', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Blackened Shrimp Tacos'), 5, 'Cook the shrimp - In a large nonstick skillet over medium-high heat, add in the oil. Once it’s hot, add the shrimp. Cook until the shrimp have slightly browned on the outside and they’ve cooked through turning pink throughout, flipping halfway through, 2-3 minutes per side', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Blackened Shrimp Tacos'), 6, 'Assemble the tortillas - Place the tortillas in a serving platter or plates. Divide the shrimp and slaw equally between the tortillas', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Blackened Shrimp Tacos'), 7, 'Garnish and serve - garnish and serve with cheese and cilantro', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Blackened Shrimp Tacos'), 8, 'Storage - Try to eat all assembled tacos that same day. If you have leftover shrimp or slaw, store in separate air-tight containers in the fridge for up to 2 days', 'ImagePath'),

		(NEWID(), dbo.fnRecipeID('Steak on the Stovetop'), 1, 'Pat the steak dry - Pat the steak dry with paper towels and season it liberally with salt all over, let rest at room temperature for 30 minutes', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Steak on the Stovetop'), 2, 'Heat the skillet - Heat a cast-iron or stainless-steel skillet large enough to hold the steak on the stove over medium-high heat until very hot and it just barely starts to smoke, about 3 minutes', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Steak on the Stovetop'), 3, 'Pat the steak dry (again) and cook - pat the steak dry again with paper towels, add the steak, and cook, pressing down to make sure it gets good contact with the pan, until a nice sear starts to form, about 2 minutes; flip over and cook for 2 minutes more. Then if you want a more well done steak, reduce the heat to medium low and continue to cook, flipping over repeatedly each minute, until the steak is as cooked as you desire', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Steak on the Stovetop'), 4, 'Baste with butter and herbs (optional) - If you want more flavor, add the butter and herbs to the pan during the last couple minutes of cooking and baste it with the butter.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Steak on the Stovetop'), 5, 'Serve - Remove the steak from the pan and let rest for a couple of minutes before slicing. If desired, sprinkle with some sea salt. Serve.', 'ImagePath'),

		(NEWID(), dbo.fnRecipeID('Stuffed Peppers'), 1, 'Preheat oven to 400°. In a small saucepan, prepare rice according to package instructions. In a large skillet over medium heat, heat oil. Cook onion until soft, about 5 minutes. Stir in tomato paste and garlic and cook until fragrant, about 1 minute more. Add ground beef and cook, breaking up meat with a wooden spoon, until no longer pink, 6 minutes. Drain fat.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Stuffed Peppers'), 2, 'Return beef mixture to skillet, then stir in cooked rice and diced tomatoes. Season with oregano, salt, and pepper. Let simmer until liquid has reduced slightly, about 5 minutes.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Stuffed Peppers'), 3, 'Place peppers cut side-up in a 9"-x-13" baking dish and drizzle with oil. Spoon beef mixture into each pepper and top with Monterey jack, then cover baking dish with foil.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Stuffed Peppers'), 4, 'Bake until peppers are tender, about 35 minutes. Uncover and bake until cheese is bubbly, 10 minutes more.', 'Image Path'),
		(NEWID(), dbo.fnRecipeID('Stuffed Peppers'), 5, 'Garnish with parsley before serving.', 'Image Path'),
		
		(NEWID(), dbo.fnRecipeID('Pasta Fazool'), 1, 'Heat oil in a skillet over medium-high heat. Cook and stir sausage in the hot skillet until browned and crumbly, about 5 minutes. Reduce heat to medium. Add diced celery and chopped onion. Cook until onions are translucent, 4-5 minutes. Add dry pasta; cook and stir for 2 minutes', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Pasta Fazool'), 2, 'Stir in tomato paste until evenly distributed, 2-3 minutes. Pour in 3 cups broth; increase heat to high and bring to a boil. Stir in red pepper flakes, oregano, salt, and pepper. Reduce heat to medium and let simmer, stirring often, for about 5 minutes. Add more broth if needed.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Pasta Fazool'), 3, 'Place chopped chard in a bowl. Cover with cold water and rinse leaves; any grit will fall to the bottom of the bowl. Transfer chard to a colander to drain briefly; add to soup. Cook and stir until leaves wilt, 2-3 minutes.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Pasta Fazool'), 4, 'Stir in white beans; continue cooking and stirring until pasta is tender, 4-5 minutes. Remove from heat and stir in grated cheese. Served topped with additional grated cheese.', 'ImagePath'),

		(NEWID(), dbo.fnRecipeID('Chicken Cacciatore'), 1, 'Preheat the oven to 350 degrees F.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Chicken Cacciatore'), 2, 'Heat olive oil in a large Dutch oven over medium-high heat; add chicken and cook until browned on the outside. Remove to a bowl to capture the juices.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Chicken Cacciatore'), 3, 'Stir in onions and mushrooms; cook for 5-6 minutes until soft. Add a big pinch of salt and pepper. Stir in garlic, rosemary, red pepper flakes, oregano, tomato sauce, and water.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Chicken Cacciatore'), 4, 'Place chicken pieces and any juices that have accumulated in the bowl on top of the cooked vegetables. Add more salt and pepper. Place pepper slices on top of the chicken.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Chicken Cacciatore'), 5, 'Cover and cook in the preheated oven for 1 hour 15 minutes.', 'ImagePath'),

		(NEWID(), dbo.fnRecipeID('Bolognese Sauce'), 1, 'Melt butter with olive oil in a large saucepan over medium heat. Add onion, celery, carrot, and 1 pinch salt; cook and stir until onion turns translucent, about 5 minutes.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Bolognese Sauce'), 2, 'Stir ground beef into vegetables; cook and stir until meat is crumbly and no longer pink, about 5 minutes. Season with 1 1/2 teaspoons salt, nutmeg, cayenne pepper, and black pepper.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Bolognese Sauce'), 3, 'Pour milk into ground beef mixture and bring to a simmer. Cook, stirring frequently, until most of the milk has evaporated and the bottom of the pan is still slightly saucy, about 5 minutes.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Bolognese Sauce'), 4, 'Increase heat to medium-high and pour in white wine; cook and stir until wine has mostly evaporated, about 5 minutes.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Bolognese Sauce'), 5, 'Pour tomatoes with juice into a large mixing bowl; crush them with your hands until they resemble a chunky sauce. Pour tomato mixture into ground beef mixture; fill the tomato can with 2 cups water and stir into sauce. Bring to a boil.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Bolognese Sauce'), 6, 'Reduce heat to low and simmer, stirring often, until mixture cooks down into a thick sauce, at least 3 hours but preferably 4 to 6 hours. Skim fat from the top of sauce if desired. Add more water if sauce is too thick. Taste and adjust seasonings before serving.', 'ImagePath'),

		(NEWID(), dbo.fnRecipeID('Lasagna'), 1, 'Make the sauce: Cook and stir ground beef and sausage in a large saucepan over medium heat until browned and crumbly, about 10 minutes. Stir in mushrooms, salt, black pepper, Italian seasoning, and pepper flakes. Increase the heat to medium-high and cook until mushrooms have given off their juices and the bottom of the pan is almost dry, 4 to 6 minutes.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Lasagna'), 2, 'Pour marinara sauce into meat mixture. (If using jarred sauce, add a little water to each jar and shake to get all sauce out of the jar; add to meat mixture.) Reduce the heat to low and simmer until meat is extremely tender, about 2 hours; add more water if sauce becomes too thick. Skim fat, then season sauce with salt and black pepper. Turn off the heat.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Lasagna'), 3, 'When the sauce is almost finished, make the pasta: Bring a large pot of salted water to a boil. Cook lasagna in the boiling water, stirring occasionally, until cooked through but firm to the bite, about 8 minutes. Drain and rinse lasagna noodles; set aside in a bowl of cold water.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Lasagna'), 4, 'While the pasta is cooking, make the filling: Whisk eggs in a large bowl, then stir in ricotta, mozzarella, Parmigiano-Reggiano, parsley, salt, black pepper, and cayenne.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Lasagna'), 5, 'When the sauce, pasta, and filling are ready, preheat the oven to 375 degrees F.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Lasagna'), 6, 'Divide sauce into fourths, noodles into thirds, and filling in half for layering. Layer ingredients in a 10x15-inch baking pan, spreading out to fill the pan, as follows: one part sauce, one part noodles, one part filling. Repeat once more. Add one part sauce, then tap the dish lightly on a sturdy work surface to settle the layers. Continue with one part noodles and one part sauce. Sprinkle remaining fresh mozzarella and Parmigiano-Reggiano over top.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Lasagna'), 7, 'Cover the baking dish with aluminum foil, making sure it does not touch the cheese. Place onto a baking sheet to catch any spills.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Lasagna'), 8, 'Bake in the preheated oven for 30 minutes. Remove the foil and continue to bake until golden brown and bubbly, 30 to 35 more minutes. Let sit for 20 minutes before serving.', 'ImagePath'),

		(NEWID(), dbo.fnRecipeID('Pork Saltimbocca'), 1, 'Remove silvery membrane from surface of the tenderloin with a sharp knife. Reserve the trimmings. Trim off the small "head" pieces of the tenderloin where there is a natural separation; this is optional. Reserve.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Pork Saltimbocca'), 2, 'Cut tenderloin in half crosswise to make 2 equal portions. Cut each half lengthwise in half to make 4 pieces. Transfer to a bowl; refrigerate while you start the sauce.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Pork Saltimbocca'), 3, 'Chop the reserved trimmings very fine. Melt butter in a pot over medium-high heat until caramelized and nicely browned, 4 or 5 minutes. Stir in broth and gelatin. Stir in water. Cook and stir over medium or medium-low heat at a low simmer until liquid is reduced by half, about 1 1/2 hours. Add more water if it reduces too quickly.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Pork Saltimbocca'), 4, 'Place pork sections between to pieces of plastic wrap. Pound to a thickness of about 1/4 to 1/8 inch thick. Remove top sheet of plastic wrap. Turn each piece over. Sprinkle generously with salt and pepper. Dust very lightly with about 2 teaspoons flour. Flip back over; sprinkle with black pepper only. Press 3 sage leaves onto surface of each piece of pork. Cover completely with prosciutto, cutting or tearing strips to fit. A bit of overlap is okay.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Pork Saltimbocca'), 5, 'Place sheet of plastic wrap back over the pork and pound very lightly to make sure the prosciutto sticks to the pork. Transfer to a plate; cover with plastic wrap. Refrigerate until chilled, at least 30 minutes.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Pork Saltimbocca'), 6, 'Strain pork broth into a bowl.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Pork Saltimbocca'), 7, 'Place skillet over high heat; add olive oil. When olive oil is hot and shimmering, place pork pieces in the oil prosciutto side down. Cook about 3 minutes. Carefully turn pieces and cook another minute. Remove skillet from heat. Transfer pork to warm serving plates.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Pork Saltimbocca'), 8, 'Blot excess oil from skillet with paper towels. Add wine and pork broth. Cook over high heat until mixture thickens and reduces by about half, 4 to 5 minutes.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Pork Saltimbocca'), 9, 'Spoon hot sauce over pork sections.', 'ImagePath'),

		(NEWID(), dbo.fnRecipeID('Beef Braciole'), 1, 'Place steaks between 2 pieces of heavy plastic; pound meat about 1/4-inch thick using a meat pounder. If a piece of meat breaks off, use it to patch a thinner area.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Beef Braciole'), 2, 'Place bread crumbs into a mixing bowl and stir in garlic, 2 tablespoons olive oil, raisins, Parmesan cheese, salt, black pepper, oregano, and egg until thoroughly combined.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Beef Braciole'), 3, 'Season steak with salt and pepper; place half the bread crumb stuffing onto the bottom 2/3 of a steak, leaving the top third of the steak without stuffing. Lightly press the stuffing onto the meat and roll the steak up into a tight roll, starting from the stuffed end. Tie 3 to 4 pieces of kitchen string around the roll to hold it together. Trim ends of string. Repeat with remaining steak and stuffing.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Beef Braciole'), 4, 'Heat 1 tablespoon olive oil in a skillet over medium-high heat. Pan-fry the steak rolls in the hot oil until well browned on all sides, 2 to 3 minutes per side. Pour in water and dissolve pan juices and browned bits of food in the water.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Beef Braciole'), 5, 'Season steak rolls with salt and pepper; add red pepper flakes and bay leaf to the water. Spread tomato sauce onto rolls. Pan liquid should cover the rolls about halfway up.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Beef Braciole'), 6, 'Bring to a boil, reduce heat to low, and simmer, covered, for 10 minutes; turn rolls over and cook covered about 10 more minutes. An instant-read meat thermometer inserted into the center of the stuffing should read at least 145 degrees F (65 degrees C). Remove from pan, transfer to a platter, and let them rest for 10 minutes.', 'ImagePath'),
		(NEWID(), dbo.fnRecipeID('Beef Braciole'), 7, 'Raise heat to medium, bring sauce to a boil, and cook, stirring often, until sauce has reduced by half, about 10 minutes. Slice the rolls crosswise. Serve arranged on a little sauce and drizzle more sauce on top.', 'ImagePath')
END

